const pera1="There once was a boy who grew bored while watching over the village sheep. He wanted to make things more exciting. So, he yelled out that he saw a wolf chasing the sheep. All the villagers came running to drive the wolf away. However, they saw no wolf. The boy was amused, but the villagers were not. They told him not to do it again. Shortly after, he repeated this antic. The villagers came running again, only to find that he was lying. Later that day, the boy really sees a wolf sneaking amongst the flock. He jumped up and called out for help. But no one came this time because they thought he was still joking around. At sunset, the villagers looked for the boy. He had not returned with their sheep. They found him crying. He told them that there really was a wolf, and the entire flock was gone. An old man came to comfort him and told him that nobody would believe a liar even when they are being honest.";

const pera2="The Greek king Midas did a good deed for a Satyr. This prompted Dionysus, the god of wine, to grant him a wish. Midas asked for everything he touched to turn to gold. Dionysus warned him not to do so, but Midas could not be swayed. Midas excitedly started touching everything and turning them into gold. Soon, he became hungry. But he couldnt eat anything because even his food turned to gold. His beloved daughter saw him in distress and ran to hug him. However, she, too, turned to gold. He realised then the golden touch was not a blessing. "
const pera3="A hungry fox once looked everywhere for food. He couldnt find anything until he stumbled upon a farmers wall. He saw big, purple, juicy grapes. He jumped as high as possible to reach the grapes. No matter how many times he tried, he failed. Finally, he gave up and went home, thinking to himself that the grapes must have been sour anyway."
const pera4="In the desert existed a rose and a cactus. The beautiful rose would take every opportunity to insult the cactus. The other plants tried to defend the cactus, but the rose was too obsessed with its own looks. There was no water during a particularly hot summer. The rose started to wither away. But the cactus had become a source of water for sparrows. The rose asked the cactus for water, and the nice cactus readily agreed. "
const pera5="An old owl would observe incidents happening around his oak tree every day. The more things he saw, the less he would speak. He heard people talking and sharing stories as well. The old owl had seen so much and heard all kinds of stories. All of these experiences helped the owl to become wiser day by day. "
const pera6="A farmer had a goose that laid one golden egg a day. He would sell the golden eggs, and they enjoyed a comfortable life. However, the farmer became greedy and wanted more than one egg a day. His wife foolishly agreed to his idea. The next day the farmer cut open the goose after it laid the golden egg. He could only find blood and guts. He realised his mistake. He now had no source of income, and the couple became poorer every day. ";
const pera7="A farmer bought a well from his neighbour to water his farm. The neighbour sold him the well but did not allow him to draw water from it. The farmer went to the emperor for justice. His courtier questioned the neighbour, who said that he had sold the well but not the water within it. The neighbour was told to either pay rent for the water to remove it all immediately. Realising that his trick didn’t work, he apologised and went home.";
const pera8="There was a man who used to travel to foreign lands. He would only talk about his adventures and deeds. He claimed he had made a great leap in a city called Rhodes. He bragged about it to no end. One listener told him to prove it physically, and he could not.";
const pera9="Four cows lived in a forest. They were good friends who did everything together. No other predators were able to kill them for food. One day, they fought and decided to graze in different directions. A tiger saw this and decided it would be easy to kill them now. The tiger hid in a bush and killed the cows one by one. ";
const pera10="There was once a young boy in school. He had wet his pants and was scared that his class would make fun of him. He noticed that the teacher and a classmate were walking towards him with a goldfish bowl. The young girl trips and drops the fishbowl in his lap. The rest of the classmates think it is her fault for wetting his pants. Later, he asks her if she did that on purpose. She tells him, “I wet my pants once too.”";
